### ISSUE TITLE
migrate to wallet-api

### ISSUE THREAD

**Issue by adrienlacombe** [LedgerHQ/platform-app-debug#5]

**Comment by chabroA** [comment]
How do we handle backward compatibility with platform-sdk (if we care, at least for a transition period)?

**Comment by adrienlacombe** [comment]
we keep it simple and publish 2 debugger apps?

**Comment by chabroA** [comment]
Indeed, that's the solution I had in mind as well. Will need to be done. Maybe by keeping [this PR](https://github.com/LedgerHQ/platform-app-debug/pull/4) open once it's done. And merge it once we decide to not support the v1 anymore.
